### ISSUE TITLE
RMB not work in "Favorites" mode

### ISSUE THREAD

**Issue by evgenius123** [koobo/HippoPlayer#11]
in the "favorites" mode, pressing the right mouse button does not minimize the HippoPlayer window. Clicking on the window minimization gadget in the window title bar works fine.
Also it not work in "directory" mode.

**Comment by koobo** [comment]
I guess this is a feature when "Favorites" mode is enabled as RMB is used to mark files as favorites. You can still minimize with RMB if you avoid clicking on top of the filebox or any of the buttons. For example, the filebox slider works.

**Comment by koobo** [comment]
Fixed in v2.53.
