### ISSUE TITLE
I got scopes to crash.

### ISSUE THREAD

**Issue by khval** [koobo/HippoPlayer#14]
so normally scopes do not open, if have AHI enabled, but by going into prefs, enabling scope while it was playing it crashed.
(this is on AmigaOS4.1)

**Comment by koobo** [comment]
In v2.52 the scopes were redone to run in multiple tasks, previously there was a single scope process. When AHI is enabled the scope windows should be empty.  No idea why it would crash on OS4...

**Comment by khval** [comment]
Just got NallePuh working on OS4.1, I have not noticed anymore crashes in scopes, using the latest HippoPlayer, I think this one is solved.
