### ISSUE TITLE
Playing mp3 using hippo player crashes on AmigaOS4.

### ISSUE THREAD

**Issue by khval** [koobo/HippoPlayer#15]
Enabling AHI only effects MOD players.

**Comment by samo790** [comment]
What a combination, just in this hours we are busy testing 2.54 beta under AOS4 :-)
MP3 files with 2.53 and 2.54 beta works on my system (Sam440 + latest AmigaOS 4.1)
I only need to set AHI in Hippo Prefs

**Comment by koobo** [comment]
It's quite difficult for me to investigate these as I don't have AOS4 running anywhere 😞

**Comment by khval** [comment]
I have 2.53, maybe something fixed in 2.54.

**Comment by khval** [comment]
mp3/mp2 works with NallePuh, 
(but I think the playback is 14bit, so sound is not good as NallePuh only supports 8bit.)
