### ISSUE TITLE
Loading of "next module" crashes 8000 0003 on 68000 when HiP GUI is hidden (rx "hide 0")

### ISSUE THREAD

**Issue by kowoba** [koobo/HippoPlayer#17]
Seems to be a bug introduced in 2.55, at least I cannot recall having this before.

Tested and confirmed on both Minimig 1.1 with 68SEC000 and A600 with 68000
I have not tried on 020+, 0003 suggests that it might not be a problem on 020+.

**Comment by khval** [comment]
Pretty sure it’s the hip-scope, have the same crash on AmigaONE-X1000 / NallePuh..

**Comment by koobo** [comment]
Thanks, I can reproduce it, will fix for the next version.

**Comment by koobo** [comment]
Fixed in v2.56
