### ISSUE TITLE
Unwanted unhiding after screenmode change

### ISSUE THREAD

**Issue by kowoba** [koobo/HippoPlayer#19]
First, thanks for 2.56 which apparently fixes all the 68000 crash issues! :)

I just want to report a mild annoyance, when I hide HiP to play in the background, and screen mode is changed, HiP always pops back up again. (I can understand how this happens, as HiP uses screennotify.library).  Would it be possible for HiP to keep track on whether it has been hidden or not, and not re-appear from a hidden state? Maybe ignore screennotify when it is hidden?

Cheers!

**Comment by koobo** [comment]
Yes, sounds like a reasonable thing to do :-)
