### ISSUE TITLE
KPlayer incorrectly stores old interrupt server pointers

### ISSUE THREAD

**Issue by dalton-tulou** [koobo/HippoPlayer#2]
kpl14.s, lines 756 and 764, stores to ``k_oldis2`` and ``k_oldis3``. Should probably be ``k_oldis3`` and ``k_oldis4``. I found this when disassembling for [Tulou Compo Player](http://www.pouet.net/prod.php?which=66908) last year. It never gave me any problems, but I think it possibly could.

**Comment by koobo** [comment]
Seems like a bug, it occurs when using the fast ram play mode. This will not return the system audio interrupt vectors to proper states after stopping playback. This may cause audio problems later on with system audio output.

**Comment by koobo** [comment]
Incidentally, "scopes/iso1.s" was also made to be used as a compoplayer, although the playing was handled by HippoPlayer in the background. It is also way uglier than yours :-)

**Comment by dalton-tulou** [comment]
Ah! I didn't know there were any scopes other than those available from the prefs menu! Knowing this I should probably have made Compo player in the form of a scope plugin for Hippoplayer. I learned a lot about modules though from studying the replayer code in detail. Thanks for releasing all the sources by the way!
