### ISSUE TITLE
Playing sid after PlaySid mode change crashes

### ISSUE THREAD

**Issue by boretrk** [koobo/HippoPlayer#20]
If I play a sid in one PlaySid mode and then try to play a sid with another mode it causes a crash.
68060 + fastmem / OS 3.1

**Comment by koobo** [comment]
Would you mind trying out this version to see if the problem still persists for you: https://www.dropbox.com/s/cw77vy2wec8qrxd/hip-beta-7.3.lha?dl=1

**Comment by boretrk** [comment]
It seems to fix the problem, nice! :+1: 

Would it be possible to get it to pick 6581/8580 automatically depending on the psid flags?

**Comment by koobo** [comment]
Great! I updated the above mentioned LHA, it has "reSID Auto" mode available in Prefs,  it should autoselect the correct SID chip.

**Comment by boretrk** [comment]
Seems to work fine. What is the behavior when a sid is flagged for both 6581 and 8580?

**Comment by koobo** [comment]
Defaults to 6581, didn't really consider what that would even mean to have both of them flagged...
