### ISSUE TITLE
Hippoplayer does something bad at exit.

### ISSUE THREAD

**Issue by khval** [koobo/HippoPlayer#3]
Hippoplayer does something bad at exit.

**Comment by khval** [comment]
680x0 emulated registers:
DATA: FFFFFFFF 5D40CD2E 5D40CDC8 00000000 00008000 00000000 00000000 0000000E 
ADDR: 6FFB8700 5D40CE0C 00000000 607FA16C 5D472380 607F7008 6FE77220 5EFF7FF8 
FPU0:                0                0                0                0 
FPU4:                0                0                0                0

**Comment by khval** [comment]
Some thing has returned a "-1" but don't know what and where.

**Comment by khval** [comment]
traced the bug back to this code.

 ifeq asm
	move.l	lockhere(a5),d1		; vapautetaan kopioitu lukko
	lore	Dos,UnLock
	lore	Exec,Forbid				; kielletään moniajo

	bsr.w	vastomaviesti			; vastataan killeriviestiin

	move.l	segment(a5),d1
	lore	Dos,UnLoadSeg			; vapautetaan omat hunkit
 endc

**Comment by khval** [comment]
Another problem found is inuitionbase is closed two times.

**Comment by khval** [comment]
DOSBase->UnLock() after Dos.library is closed.

**Comment by khval** [comment]
I'm not sure about UnLoadSeg part, maybe I should keep it open, until I looked closer at that code.

**Comment by koobo** [comment]
Nice finds! I guess using libraries after closing do not crash because both dos and intuition are ROM based and will never be unloaded even if they are closed unnecessarily many times.

The UnLoadSeg is there to free the program code from memory.

**Comment by khval** [comment]
This is critical bug under OS4, program was stopped by Grim Reaper, so I know there was problem on exit, but where the problem was not so easy. As I'm having problem finding the lines it crash on, there is one thing missing in Grim Reaper and that is "PC" register, I don't know where to obtain that with the exception of maybe a PC value pushed to stack. It did crash once or twice under EUAE as well, well there is few new factor, I compiled it with vasm instead of AsmOne, having added some extra code into HippoPlayer, running it under OS4, with its "simple" memory protection. That’s a lot more then what is under OS3.

**Comment by khval** [comment]
>The UnLoadSeg is there to free the program code from memory.

That sound like something that should be last thing to happen.

**Comment by koobo** [comment]
I think that's why there is a Forbid() there before UnLoadSeg().

**Comment by koobo** [comment]
According to samo79 crash at exit

**Comment by koobo** [comment]
The issue seems to be that on OS4 the "UnloadSeg" must be the absolute last thing to call.

**Comment by khval** [comment]
I have not noticed any crashes at exit on latest hippoplayer. I think this issue is solved.
