### ISSUE TITLE
File requester sorts directories only after touching the scroll bar

### ISSUE THREAD

**Issue by sauhir** [koobo/HippoPlayer#5]
I have WB 3.1 and I have a mod folder with subfolders A-Z. When I click "New" or "Add" the directories are in the order they are in the hard drive so basically random. When I touch the scroll bar they arrange themselves into alphabetic order. Is is possible to have them open as sorted or is that a Workbench provided requester?

**Comment by koobo** [comment]
Hi! Sorry about the delay, I just noticed this only now :-)
Yes, this is a feature of the "reqtools.library" provided file requester as far as I remember.

**Comment by koobo** [comment]
Forgot to mention, with Reqtools Prefs application this can be configured.

**Comment by sauhir** [comment]
Thanks I'll check that out! And thanks for your continued support and development of HippoPlayer! It still remains in regular use for me.
