### ISSUE TITLE
No Scope Updates when screen is not active

### ISSUE THREAD

**Issue by TomCat666** [koobo/HippoPlayer#6]
Now that we have multiple monitor support with P96 libraries it is possible to have HippoPlayer playing in its own Native screen and have RTG Workbench active at the same time on the other monitor. But as soon as the Screen on which HippoPlayer is placed is not active anymore the Scopes stop updating, only the timer updates.
Would it be possible to add an option for the Scopes to update at all times regardless if the screen is active or not?

**Comment by koobo** [comment]
I'm investigating a solution :-)

**Comment by TomCat666** [comment]
Thank you ! :)

**Comment by TomCat666** [comment]
Still a problem in the newest version. If a scope is always visible then it is refreshing ok, but as soon as a module doesn't use scope and next use uses it again it is disabled again. So for it to be active all modules that you play must support visualisation through scope, as soon as one doesn't it gets disabled and you have to click on it to enable it again.

**Comment by koobo** [comment]
Ok! I admit the change was quite haphazard :-) I will have another look at it.

**Comment by koobo** [comment]
How about if you activate the scope with LMB, it will remember this until application is closed?

**Comment by TomCat666** [comment]
Nope, when the Scope is closed (because a mod file doesnt support it) and then reopened with another mode file, it is not activated anymore.

**Comment by TomCat666** [comment]
Here is a video:

http://pc.sux.org/tomcat/HippoActivate.mkv

I play 3 modules in a row (each 22 seconds), first one has Scopes, 2nd one doesn't, 3rd again has scopes... when i click on the scope and then go to the right monitor everything is ok, it plays on, then the scope dissapears when 2nd mod starts and after the 3rd module starts the scope appears but it is not active (it has hippo in it), until I activate the screen by going to it with the mouse cursor...

**Comment by koobo** [comment]
Oh sorry I was unclear. I understand your problem, I was trying to offer a solution. Would it work for you if the manual activation stayed for the remaining time application is open, so you only need to do LMB click once in the scope window?

**Comment by TomCat666** [comment]
Hehe, yeah, misunderstanding on my side. Yes, it would be a good solution :) Thank you!

**Comment by koobo** [comment]
Solution available in v2.49. I still don't like it too much but maybe it works.

**Comment by TomCat666** [comment]
Thank you. Works perfectly ! :)
