### ISSUE TITLE
Random Play goes through all sub-tunes

### ISSUE THREAD

**Issue by TomCat666** [koobo/HippoPlayer#9]
Hi

Not sure if this is normal behaviour but when doing a RandomPlay the player plays all subTunes in one module in order before going to the next tune, regardless of what the Timeout is set to. If I set timeout to 2 minutes and a module has 10 subtunes that are 1 minute long it will play all subtunes through and then go to the next module.
Is it possible to have a settings to not go through subtunes  in Random or Next song play and just play the first subTune, which is the main one?

**Comment by koobo** [comment]
Fixed in v2.53 (13.7.2022)
